---
title: "Calculation of Incremental Cost-Effectiveness Ratios"
author: "Fernando Alarid-Escudero, Caleb Easterly, Eva Enns, and the DARTH Team"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.align = "center"
)
```

# ICERS

**information here**

# Data

```{r}
library(dampack)
data("euro_prostate")

library(knitr)
library(kableExtra)
library(dplyr)
euro_prostate %>%
  arrange(Effect_QALYS) %>%
  kable() %>%
  kable_styling()
```

# Calculate ICERs

```{r}
icer_table <- calculate_icers(cost = euro_prostate$Cost_USD,
                              effect = euro_prostate$Effect_QALYS,
                              strategies = euro_prostate$Strategy_short)
head(icer_table)
```

The default view is by status (non-dominated, extended dominated, or dominated).

```{r}
icer_table %>%
  kable() %>%
  kable_styling()
```

We can also sort by cost:

```{r}
library(dplyr)
icer_table %>%
  arrange(Cost)
```

# Plot

```{r}
plot(icer_table)
```
